// ─── GET /api/cron/weekly-insights ────────────────────────────────────────────
// Vercel cron — runs every Monday at 7am AEST (Sunday 21:00 UTC).
// Fetches financial + ITP data for all projects, generates AI summaries,
// and composes a weekly email. Requires X-Cron-Secret header.
//
// Email sending: logs HTML to console. Wire up Resend or SMTP when ready
// by setting RESEND_API_KEY or SMTP_* env vars.

import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
);

const FLEEK_COMPANY_ID = process.env.FLEEK_COMPANY_ID ?? "";
const EMAIL_TO         = "jordan@fleekconstructions.au";

function esc(s: string | null | undefined): string {
  return (s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function buildEmailHtml(
  weekOf: string,
  sections: { projectName: string; summary: string; itpGaps: string[]; completionPct: number | null }[]
): string {
  const projectRows = sections.map(s => `
    <div style="margin-bottom:24px;border:1px solid #e5e7eb;border-radius:8px;overflow:hidden">
      <div style="background:#1f3864;color:#fff;padding:10px 16px">
        <span style="font-size:13px;font-weight:700">${esc(s.projectName)}</span>
        ${s.completionPct != null
          ? `<span style="float:right;font-size:11px;opacity:0.8">${s.completionPct}% claimed</span>`
          : ""}
      </div>
      <div style="padding:14px 16px;background:#fff">
        <p style="margin:0 0 10px 0;font-size:13px;color:#374151;line-height:1.6">${esc(s.summary)}</p>
        ${s.itpGaps.length > 0
          ? `<div style="background:#fffbeb;border:1px solid #fde68a;border-radius:6px;padding:8px 12px">
               <p style="margin:0;font-size:11px;font-weight:700;color:#92400e">⚠ ITP Gaps: ${s.itpGaps.join(", ")}</p>
             </div>`
          : `<p style="margin:0;font-size:11px;color:#16a34a">✓ No ITP gaps identified</p>`}
      </div>
    </div>`).join("");

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><title>Fleek ITP Insights — Week of ${esc(weekOf)}</title></head>
<body style="font-family:Arial,Helvetica,sans-serif;max-width:680px;margin:0 auto;padding:24px;color:#1a1a1a">
  <div style="border-bottom:3px solid #1f3864;padding-bottom:16px;margin-bottom:24px">
    <p style="margin:0;font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:0.1em;color:#1f3864">Fleek Constructions</p>
    <h1 style="margin:4px 0 0 0;font-size:20px;font-weight:700">ITP Insights — Week of ${esc(weekOf)}</h1>
    <p style="margin:6px 0 0 0;font-size:12px;color:#6b7280">AI-generated morning briefing across all active projects</p>
  </div>
  ${projectRows || "<p style='color:#6b7280'>No project data available.</p>"}
  <div style="border-top:1px solid #e5e7eb;margin-top:24px;padding-top:12px">
    <p style="margin:0;font-size:10px;color:#9ca3af">Generated by Fleek ITP Reviewer · ${new Date().toLocaleDateString("en-AU", { day: "2-digit", month: "long", year: "numeric" })}</p>
  </div>
</body>
</html>`;
}

export async function GET(request: NextRequest) {
  // ── Auth ──────────────────────────────────────────────────────────────────
  const cronSecret = process.env.CRON_SECRET;
  const provided   = request.headers.get("x-cron-secret");
  if (!cronSecret || provided !== cronSecret) {
    return NextResponse.json({ error: "Unauthorized." }, { status: 401 });
  }

  if (!FLEEK_COMPANY_ID) {
    return NextResponse.json({ error: "FLEEK_COMPANY_ID not configured." }, { status: 500 });
  }

  const weekOf = new Date().toLocaleDateString("en-AU", { day: "2-digit", month: "long", year: "numeric" });
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "https://itp-reviewer.vercel.app";

  // ── Fetch project list from Supabase (hidden_projects table or dashboard/projects) ──
  // We don't have a Procore token in cron context, so we pull project IDs from
  // review_records instead (projects that have ever been reviewed).
  const { data: projectRows } = await supabase
    .from("review_records")
    .select("procore_project_id, company_id")
    .eq("company_id", FLEEK_COMPANY_ID)
    .order("reviewed_at", { ascending: false });

  // Deduplicate project IDs
  const projectIds = [...new Set((projectRows ?? []).map(r => String(r.procore_project_id)))].slice(0, 20);

  if (projectIds.length === 0) {
    console.log("[weekly-insights] No projects found in review_records.");
    return NextResponse.json({ message: "No projects to process.", week_of: weekOf });
  }

  // ── Check for existing today snapshots ────────────────────────────────────
  const today = new Date().toISOString().slice(0, 10);
  const { data: existingSnaps } = await supabase
    .from("project_financial_snapshots")
    .select("procore_project_id, summary, itp_gaps, completion_pct")
    .eq("company_id", FLEEK_COMPANY_ID)
    .eq("snapshot_date", today);

  const snapshotMap = new Map(
    (existingSnaps ?? []).map(s => [String(s.procore_project_id), s])
  );

  // ── Also fetch project names from review_records ──────────────────────────
  const { data: nameRows } = await supabase
    .from("review_records")
    .select("procore_project_id, review_data")
    .eq("company_id", FLEEK_COMPANY_ID)
    .not("review_data", "is", null);

  const nameMap = new Map<string, string>();
  for (const row of nameRows ?? []) {
    const pid = String(row.procore_project_id);
    if (!nameMap.has(pid)) {
      const header = (row.review_data as Record<string, unknown>)?.inspection_header as Record<string, unknown> | undefined;
      if (header?.project_name) nameMap.set(pid, String(header.project_name));
    }
  }

  // ── Build email sections ─────────────────────────────────────────────────
  const sections: { projectName: string; summary: string; itpGaps: string[]; completionPct: number | null }[] = [];
  const results: string[] = [];

  for (const pid of projectIds) {
    const snap = snapshotMap.get(pid);
    const projectName = nameMap.get(pid) ?? `Project ${pid}`;

    if (snap) {
      // Use existing today snapshot
      sections.push({
        projectName,
        summary:      String(snap.summary ?? ""),
        itpGaps:      Array.isArray(snap.itp_gaps) ? snap.itp_gaps as string[] : [],
        completionPct: typeof snap.completion_pct === "number" ? snap.completion_pct : null,
      });
      results.push(`${pid}: used cached snapshot`);
      continue;
    }

    // No snapshot today — skip (cron has no Procore token)
    // Log for awareness; a manual Refresh All from the UI should generate them
    results.push(`${pid}: no snapshot for today — run Refresh All from dashboard`);
  }

  // ── Compose email ─────────────────────────────────────────────────────────
  const emailHtml = buildEmailHtml(weekOf, sections);
  const subject   = `Fleek ITP Insights — Week of ${weekOf}`;

  // ── Send email (Resend if available, otherwise log) ───────────────────────
  let emailStatus = "not_sent";

  const resendKey = process.env.RESEND_API_KEY;
  if (resendKey) {
    try {
      const sendRes = await fetch("https://api.resend.com/emails", {
        method:  "POST",
        headers: { Authorization: `Bearer ${resendKey}`, "Content-Type": "application/json" },
        body:    JSON.stringify({
          from:    "Fleek ITP Reviewer <noreply@fleekconstructions.au>",
          to:      [EMAIL_TO],
          subject,
          html:    emailHtml,
        }),
        signal:  AbortSignal.timeout(15_000),
      });
      emailStatus = sendRes.ok ? "sent_resend" : `resend_error_${sendRes.status}`;
    } catch (err) {
      emailStatus = `resend_exception: ${err instanceof Error ? err.message : String(err)}`;
    }
  } else {
    // Log HTML so it can be wired up later
    console.log(`[weekly-insights] Email not configured. Subject: ${subject}`);
    console.log(`[weekly-insights] Recipient: ${EMAIL_TO}`);
    console.log(`[weekly-insights] Set RESEND_API_KEY to enable sending.`);
    console.log(`[weekly-insights] Dashboard to trigger refreshes: ${baseUrl}/dashboard`);
    emailStatus = "logged_no_sender";
  }

  return NextResponse.json({
    week_of:      weekOf,
    projects:     projectIds.length,
    with_summary: sections.length,
    email_to:     EMAIL_TO,
    email_status: emailStatus,
    results,
  });
}
